// Generated by spider on 2025-09-21 12:06:48.828804

part of 'resources.dart';

class SvgGifs {
  SvgGifs._();

  static const String aaAni = 'assets/gifs/aa_ani.gif';
  static const String aaLogo = 'assets/gifs/aa_logo.gif';
  static const String aaaclipbut1 = 'assets/gifs/aaaclipbut1.gif';
  static const String aaextreme = 'assets/gifs/aaextreme.gif';
  static const String abWhite = 'assets/gifs/ab-white.gif';
  static const String abYr = 'assets/gifs/ab-yr.gif';
  static const String ab = 'assets/gifs/ab.gif';
  static const String ab03 = 'assets/gifs/ab03.gif';
  static const String abcdirBanner6 = 'assets/gifs/abcdir-banner6.gif';
  static const String abcgiant = 'assets/gifs/abcgiant.gif';
  static const String aboutg = 'assets/gifs/aboutg.gif';
  static const String abrbus = 'assets/gifs/abrbus.gif';
  static const String abrowser = 'assets/gifs/abrowser.gif';
  static const String absfree = 'assets/gifs/absfree.gif';
  static const String absoftLogo = 'assets/gifs/absoft_logo.gif';
  static const String absoluteFtp = 'assets/gifs/absolute_ftp.gif';
  static const String absolutely = 'assets/gifs/absolutely.gif';
  static const String acButtonFrobert = 'assets/gifs/ac-button-frobert.gif';
  static const String acab = 'assets/gifs/acab.gif';
  static const String acapickels = 'assets/gifs/acapickels.gif';
  static const String acaza = 'assets/gifs/acaza.gif';
  static const String accelerating = 'assets/gifs/accelerating.gif';
  static const String accursedFarmsAlienBlink =
      'assets/gifs/accursed-farms-alien-blink.gif';
  static const String acdsee = 'assets/gifs/acdsee.gif';
  static const String aceftp = 'assets/gifs/aceftp.gif';
  static const String aceplay = 'assets/gifs/aceplay.gif';
  static const String achbus = 'assets/gifs/achbus.gif';
  static const String acid = 'assets/gifs/acid.gif';
  static const String acidProd = 'assets/gifs/acid_prod.gif';
  static const String acidawards24 = 'assets/gifs/acidawards24.gif';
  static const String acidfonts = 'assets/gifs/acidfonts.gif';
  static const String acidglossNet = 'assets/gifs/acidgloss.net.gif';
  static const String acidicdarkness = 'assets/gifs/acidicdarkness.gif';
  static const String acidlemon = 'assets/gifs/acidlemon.gif';
  static const String acmelogo = 'assets/gifs/acmelogo.gif';
  static const String activator = 'assets/gifs/activator.gif';
  static const String activewin = 'assets/gifs/activewin.gif';
  static const String activeworlds = 'assets/gifs/activeworlds.gif';
  static const String addchannel = 'assets/gifs/addchannel.gif';
  static const String addesigner = 'assets/gifs/addesigner.gif';
  static const String addit1 = 'assets/gifs/addit1.gif';
  static const String addme = 'assets/gifs/addme.gif';
  static const String addmecom = 'assets/gifs/addmecom.gif';
  static const String addpro = 'assets/gifs/addpro.gif';
  static const String adecline = 'assets/gifs/adecline.gif';
  static const String adlogo = 'assets/gifs/adlogo.gif';
  static const String adobeAsanim1 = 'assets/gifs/adobe_asanim1.gif';
  static const String adobeAtmosphere = 'assets/gifs/adobe_atmosphere.gif';
  static const String adobeAuthorware = 'assets/gifs/adobe_authorware.gif';
  static const String adobeDreamweaver = 'assets/gifs/adobe_dreamweaver.gif';
  static const String adobeFireworks = 'assets/gifs/adobe_fireworks.gif';
  static const String adobeFlashGet = 'assets/gifs/adobe_flash_get.gif';
  static const String adobeFpbutton = 'assets/gifs/adobe_fpbutton.gif';
  static const String adobeGetAuthorware =
      'assets/gifs/adobe_get_authorware.gif';
  static const String adobeGetFlashPlayer =
      'assets/gifs/adobe_get_flash_player.gif';
  static const String adobeGetFlashplayer =
      'assets/gifs/adobe_get_flashplayer.gif';
  static const String adobeGetFlashplayer2 =
      'assets/gifs/adobe_get_flashplayer2.gif';
  static const String adobeGetShockPlayer =
      'assets/gifs/adobe_get_shock_player.gif';
  static const String adobeGetShockPlayer2 =
      'assets/gifs/adobe_get_shock_player2.gif';
  static const String adobeGetShockwave = 'assets/gifs/adobe_get_shockwave.gif';
  static const String adobeGetShockwave2 =
      'assets/gifs/adobe_get_shockwave2.gif';
  static const String adobeGetShockwave20010813 =
      'assets/gifs/adobe_get_shockwave_20010813.gif';
  static const String adobeGetShockwaveAuthorware =
      'assets/gifs/adobe_get_shockwave_authorware.gif';
  static const String adobeGetacro = 'assets/gifs/adobe_getacro.gif';
  static const String adobeGetacroread = 'assets/gifs/adobe_getacroread.gif';
  static const String adobeGetareader = 'assets/gifs/adobe_getareader.gif';
  static const String adobeGetas2 = 'assets/gifs/adobe_getas2.gif';
  static const String adobeGetauthorware =
      'assets/gifs/adobe_getauthorware.gif';
  static const String adobeGetereader = 'assets/gifs/adobe_getereader.gif';
  static const String adobeGetflash = 'assets/gifs/adobe_getflash.gif';
  static const String adobeGetflash2 = 'assets/gifs/adobe_getflash2.gif';
  static const String adobeGetflash3 = 'assets/gifs/adobe_getflash3.gif';
  static const String adobeGetflash4 = 'assets/gifs/adobe_getflash4.gif';
  static const String adobeGetflashp = 'assets/gifs/adobe_getflashp.gif';
  static const String adobeGolive = 'assets/gifs/adobe_golive.gif';
  static const String adobeGolive2 = 'assets/gifs/adobe_golive2.gif';
  static const String adobeMwmDir = 'assets/gifs/adobe_mwm_dir.gif';
  static const String adobeMwmDirmw = 'assets/gifs/adobe_mwm_dirmw.gif';
  static const String adobeMwmDw = 'assets/gifs/adobe_mwm_dw.gif';
  static const String adobeMwmDwmx = 'assets/gifs/adobe_mwm_dwmx.gif';
  static const String adobeMwmFla = 'assets/gifs/adobe_mwm_fla.gif';
  static const String adobeMwmFlmx = 'assets/gifs/adobe_mwm_flmx.gif';
  static const String adobeMwmFw = 'assets/gifs/adobe_mwm_fw.gif';
  static const String adobeMwmFwmx = 'assets/gifs/adobe_mwm_fwmx.gif';
  static const String adobePhoto = 'assets/gifs/adobe_photo.gif';
  static const String adobeSvg = 'assets/gifs/adobe_svg.gif';
  static const String adobesvg = 'assets/gifs/adobesvg.gif';
  static const String adultchat = 'assets/gifs/adultchat.gif';
  static const String aedit = 'assets/gifs/aedit.gif';
  static const String afBoton9 = 'assets/gifs/af-boton9.gif';
  static const String afPixel = 'assets/gifs/af-pixel.gif';
  static const String afPsylab = 'assets/gifs/af-psylab.gif';
  static const String affcrack = 'assets/gifs/affcrack.gif';
  static const String affection = 'assets/gifs/affection.gif';
  static const String africapt = 'assets/gifs/africapt.gif';
  static const String afro = 'assets/gifs/afro.gif';
  static const String afs = 'assets/gifs/afs.gif';
  static const String afxbutton1 = 'assets/gifs/afxbutton1.gif';
  static const String agag = 'assets/gifs/agag.gif';
  static const String agagamem = 'assets/gifs/agagamem.gif';
  static const String agplv388x31 = 'assets/gifs/agplv3-88x31.gif';
  static const String ah = 'assets/gifs/ah.gif';
  static const String aiboton = 'assets/gifs/aiboton.gif';
  static const String aikiweb = 'assets/gifs/aikiweb.gif';
  static const String aim = 'assets/gifs/aim.gif';
  static const String aimlink = 'assets/gifs/aimlink.gif';
  static const String aimthings = 'assets/gifs/aimthings.gif';
  static const String airmailnow = 'assets/gifs/airmailnow.gif';
  static const String akageobutton2 = 'assets/gifs/akageobutton2.gif';
  static const String akmmosBan = 'assets/gifs/akmmos_ban.gif';
  static const String aladdinnow = 'assets/gifs/aladdinnow.gif';
  static const String aldema2 = 'assets/gifs/aldema2.gif';
  static const String aleash = 'assets/gifs/aleash.gif';
  static const String alertra = 'assets/gifs/alertra.gif';
  static const String alfart = 'assets/gifs/alfart.gif';
  static const String alienow = 'assets/gifs/alienow.gif';
  static const String alienwareButton = 'assets/gifs/alienware_button.gif';
  static const String alink02a = 'assets/gifs/alink02a.gif';
  static const String allfree = 'assets/gifs/allfree.gif';
  static const String allfreethings = 'assets/gifs/allfreethings.gif';
  static const String alltits = 'assets/gifs/alltits.gif';
  static const String alohabook = 'assets/gifs/alohabook.gif';
  static const String alphaIi = 'assets/gifs/alpha-ii.gif';
  static const String alphaCentauri = 'assets/gifs/alpha_centauri.gif';
  static const String altavista = 'assets/gifs/altavista.gif';
  static const String altavista2 = 'assets/gifs/altavista2.gif';
  static const String amatsuki = 'assets/gifs/amatsuki.gif';
  static const String amazingFreeStuff = 'assets/gifs/amazing_free_stuff.gif';
  static const String amazon88x31 = 'assets/gifs/amazon-88x31.gif';
  static const String amazon = 'assets/gifs/amazon.gif';
  static const String amazon2 = 'assets/gifs/amazon2.gif';
  static const String amazon3 = 'assets/gifs/amazon3.gif';
  static const String amazon4 = 'assets/gifs/amazon4.gif';
  static const String amazon5 = 'assets/gifs/amazon5.gif';
  static const String amdNow = 'assets/gifs/amd_now.gif';
  static const String amdPowered = 'assets/gifs/amd_powered.gif';
  static const String americasdecline = 'assets/gifs/americasdecline.gif';
  static const String amftpnow = 'assets/gifs/amftpnow.gif';
  static const String amigaNews = 'assets/gifs/amiga-news.gif';
  static const String amigaNews2 = 'assets/gifs/amiga-news2.gif';
  static const String amiga = 'assets/gifs/amiga.gif';
  static const String amiga1200 = 'assets/gifs/amiga1200.gif';
  static const String amigaAnim = 'assets/gifs/amiga_anim.gif';
  static const String amigaFriendly = 'assets/gifs/amiga_friendly.gif';
  static const String amigaPower = 'assets/gifs/amiga_power.gif';
  static const String amigaRc5 = 'assets/gifs/amiga_rc5.gif';
  static const String amigaamp = 'assets/gifs/amigaamp.gif';
  static const String amigademo = 'assets/gifs/amigademo.gif';
  static const String amigaemu = 'assets/gifs/amigaemu.gif';
  static const String amigaos = 'assets/gifs/amigaos.gif';
  static const String amigapow = 'assets/gifs/amigapow.gif';
  static const String amigatm = 'assets/gifs/amigatm.gif';
  static const String amircNow = 'assets/gifs/amirc_now.gif';
  static const String amiw2 = 'assets/gifs/amiw2.gif';
  static const String amyuoy1 = 'assets/gifs/amyuoy1.gif';
  static const String anClan88 = 'assets/gifs/an-clan-88.gif';
  static const String anarchyNow = 'assets/gifs/anarchy-now.gif';
  static const String anarchy = 'assets/gifs/anarchy.gif';
  static const String anarchy1 = 'assets/gifs/anarchy1.gif';
  static const String anarchynow = 'assets/gifs/anarchynow.gif';
  static const String andysart = 'assets/gifs/andysart.gif';
  static const String angel99 = 'assets/gifs/angel99.gif';
  static const String angelcat3 = 'assets/gifs/angelcat3.gif';
  static const String angelfire = 'assets/gifs/angelfire.gif';
  static const String angelkiss = 'assets/gifs/angelkiss.gif';
  static const String angellogo = 'assets/gifs/angellogo.gif';
  static const String angellovebox = 'assets/gifs/angellovebox.gif';
  static const String angelzButton = 'assets/gifs/angelz_button.gif';
  static const String angyBan27 = 'assets/gifs/angy_ban2_7.gif';
  static const String aniFace = 'assets/gifs/ani_face.gif';
  static const String aniPassale = 'assets/gifs/ani_passale.gif';
  static const String aniback1g = 'assets/gifs/aniback1g.gif';
  static const String anibanner = 'assets/gifs/anibanner.gif';
  static const String anibutton = 'assets/gifs/anibutton.gif';
  static const String anibuttonscifi = 'assets/gifs/anibuttonscifi.gif';
  static const String anibuy3 = 'assets/gifs/anibuy3.gif';
  static const String anigif = 'assets/gifs/anigif.gif';
  static const String anigifs = 'assets/gifs/anigifs.gif';
  static const String anihome112g = 'assets/gifs/anihome112g.gif';
  static const String anilinkwired = 'assets/gifs/anilinkwired.gif';
  static const String anilogo = 'assets/gifs/anilogo.gif';
  static const String anima = 'assets/gifs/anima.gif';
  static const String animagButton = 'assets/gifs/animag_button.gif';
  static const String animatedbutton = 'assets/gifs/animatedbutton.gif';
  static const String animation51 = 'assets/gifs/animation51.gif';
  static const String animationsBackgroundsClipart =
      'assets/gifs/animations-backgrounds-clipart.gif';
  static const String animationshop = 'assets/gifs/animationshop.gif';
  static const String animationstation = 'assets/gifs/animationstation.gif';
  static const String animbat = 'assets/gifs/animbat.gif';
  static const String animbutton1 = 'assets/gifs/animbutton1.gif';
  static const String anime100 = 'assets/gifs/anime100.gif';
  static const String anime100games = 'assets/gifs/anime100games.gif';
  static const String anime100green = 'assets/gifs/anime100green.gif';
  static const String anime100red = 'assets/gifs/anime100red.gif';
  static const String anime50 = 'assets/gifs/anime50.gif';
  static const String animegay = 'assets/gifs/animegay.gif';
  static const String animeland = 'assets/gifs/animeland.gif';
  static const String animenation88x31 = 'assets/gifs/animenation-88x31.gif';
  static const String animenation = 'assets/gifs/animenation.gif';
  static const String animexchange = 'assets/gifs/animexchange.gif';
  static const String animicon = 'assets/gifs/animicon.gif';
  static const String aninext1g = 'assets/gifs/aninext1g.gif';
  static const String anipitstop = 'assets/gifs/anipitstop.gif';
  static const String annu = 'assets/gifs/annu.gif';
  static const String anonymize = 'assets/gifs/anonymize.gif';
  static const String another = 'assets/gifs/another.gif';
  static const String anreise = 'assets/gifs/anreise.gif';
  static const String anthrax = 'assets/gifs/anthrax.gif';
  static const String antiButton = 'assets/gifs/anti_button.gif';
  static const String antiaol = 'assets/gifs/antiaol.gif';
  static const String anticodeandrun = 'assets/gifs/anticodeandrun.gif';
  static const String anticodeandrun2 = 'assets/gifs/anticodeandrun2.gif';
  static const String antifa = 'assets/gifs/antifa.gif';
  static const String antihentai = 'assets/gifs/antihentai.gif';
  static const String antinazi = 'assets/gifs/antinazi.gif';
  static const String antinft = 'assets/gifs/antinft.gif';
  static const String antisocialism = 'assets/gifs/antisocialism.gif';
  static const String antispicecool = 'assets/gifs/antispicecool.gif';
  static const String any = 'assets/gifs/any.gif';
  static const String any1 = 'assets/gifs/any1.gif';
  static const String any2 = 'assets/gifs/any2.gif';
  static const String any88x31 = 'assets/gifs/any88x31.gif';
  static const String anyBrowser = 'assets/gifs/any_browser.gif';
  static const String anyBrowserAt = 'assets/gifs/any_browser_at.gif';
  static const String anyBrowserEnhanced =
      'assets/gifs/any_browser_enhanced.gif';
  static const String anyBrowserNow = 'assets/gifs/any_browser_now.gif';
  static const String anybestviewed = 'assets/gifs/anybestviewed.gif';
  static const String anybrow = 'assets/gifs/anybrow.gif';
  static const String anybrowser = 'assets/gifs/anybrowser.gif';
  static const String anybrowser2 = 'assets/gifs/anybrowser2.gif';
  static const String anybrowser3 = 'assets/gifs/anybrowser3.gif';
  static const String anybrowser4 = 'assets/gifs/anybrowser4.gif';
  static const String anybrowser5 = 'assets/gifs/anybrowser5.gif';
  static const String anybrowser6 = 'assets/gifs/anybrowser6.gif';
  static const String anybrowser7 = 'assets/gifs/anybrowser7.gif';
  static const String anydamn = 'assets/gifs/anydamn.gif';
  static const String anyieAnim = 'assets/gifs/anyie_anim.gif';
  static const String anythingbut = 'assets/gifs/anythingbut.gif';
  static const String ao3gif = 'assets/gifs/ao3gif.gif';
  static const String aolSucks = 'assets/gifs/aol-sucks.gif';
  static const String aolUser = 'assets/gifs/aol-user.gif';
  static const String aol = 'assets/gifs/aol.gif';
  static const String aolInstant3 = 'assets/gifs/aol_instant3.gif';
  static const String aolenterprise = 'assets/gifs/aolenterprise.gif';
  static const String aolie = 'assets/gifs/aolie.gif';
  static const String aolim = 'assets/gifs/aolim.gif';
  static const String aolnetfind = 'assets/gifs/aolnetfind.gif';
  static const String aolsux = 'assets/gifs/aolsux.gif';
  static const String aoltosA = 'assets/gifs/aoltos_a.gif';
  static const String apacheForrest = 'assets/gifs/apache-forrest.gif';
  static const String apacheModPerl = 'assets/gifs/apache-mod_perl.gif';
  static const String apachePowered = 'assets/gifs/apache-powered.gif';
  static const String apacheThanks = 'assets/gifs/apache-thanks.gif';
  static const String apcProtect = 'assets/gifs/apc-protect.gif';
  static const String apc = 'assets/gifs/apc.gif';
  static const String apcpagegr = 'assets/gifs/apcpagegr.gif';
  static const String apngasm = 'assets/gifs/apngasm.gif';
  static const String aponow = 'assets/gifs/aponow.gif';
  static const String appleCollect = 'assets/gifs/apple-collect.gif';
  static const String appleCollect2 = 'assets/gifs/apple-collect2.gif';
  static const String appleFatalError = 'assets/gifs/apple_fatal_error.gif';
  static const String appleSpecial1 = 'assets/gifs/apple_special1.gif';
  static const String appledust = 'assets/gifs/appledust.gif';
  static const String applelinks = 'assets/gifs/applelinks.gif';
  static const String applelinks2 = 'assets/gifs/applelinks2.gif';
  static const String applestore = 'assets/gifs/applestore.gif';
  static const String applyLogo = 'assets/gifs/apply_logo.gif';
  static const String applyLogo2 = 'assets/gifs/apply_logo2.gif';
  static const String approved = 'assets/gifs/approved.gif';
  static const String approved508 = 'assets/gifs/approved_508.gif';
  static const String approvedasacpmember =
      'assets/gifs/approvedasacpmember.gif';
  static const String aqnow = 'assets/gifs/aqnow.gif';
  static const String arachne = 'assets/gifs/arachne.gif';
  static const String arachne2 = 'assets/gifs/arachne2.gif';
  static const String arachno = 'assets/gifs/arachno.gif';
  static const String arcadevirusAv4 = 'assets/gifs/arcadevirus_av4.gif';
  static const String archivers = 'assets/gifs/archivers.gif';
  static const String archivorock = 'assets/gifs/archivorock.gif';
  static const String archlinux = 'assets/gifs/archlinux.gif';
  static const String arcnet = 'assets/gifs/arcnet.gif';
  static const String arena = 'assets/gifs/arena.gif';
  static const String arizona = 'assets/gifs/arizona.gif';
  static const String armed = 'assets/gifs/armed.gif';
  static const String armorgames = 'assets/gifs/armorgames.gif';
  static const String artofdawn = 'assets/gifs/artofdawn.gif';
  static const String arttoday = 'assets/gifs/arttoday.gif';
  static const String artwanted = 'assets/gifs/artwanted.gif';
  static const String asacp = 'assets/gifs/asacp.gif';
  static const String asciicat = 'assets/gifs/asciicat.gif';
  static const String asco88x313 = 'assets/gifs/asco_88x31_3.gif';
  static const String asexualsNow = 'assets/gifs/asexuals_now.gif';
  static const String asswolfBanner = 'assets/gifs/asswolf_banner.gif';
  static const String asswolfTxt = 'assets/gifs/asswolf_txt.gif';
  static const String astaSmall = 'assets/gifs/asta_small.gif';
  static const String asusClr19970504 = 'assets/gifs/asus-clr_19970504.gif';
  static const String atariRead = 'assets/gifs/atari-read.gif';
  static const String atari = 'assets/gifs/atari.gif';
  static const String atariTimes = 'assets/gifs/atari_times.gif';
  static const String atariWebring = 'assets/gifs/atari_webring.gif';
  static const String atarilogo = 'assets/gifs/atarilogo.gif';
  static const String atemplate8831 = 'assets/gifs/atemplate88_31.gif';
  static const String ath2404 = 'assets/gifs/ath2404.gif';
  static const String atlas = 'assets/gifs/atlas.gif';
  static const String atmturbo = 'assets/gifs/atmturbo.gif';
  static const String atomic = 'assets/gifs/atomic.gif';
  static const String atomicansLink = 'assets/gifs/atomicans_link.gif';
  static const String atomicdusticon = 'assets/gifs/atomicdusticon.gif';
  static const String atomicfireball = 'assets/gifs/atomicfireball.gif';
  static const String atomicwarriors = 'assets/gifs/atomicwarriors.gif';
  static const String auction88x31 = 'assets/gifs/auction88x31.gif';
  static const String auron = 'assets/gifs/auron.gif';
  static const String auto = 'assets/gifs/auto.gif';
  static const String autocat = 'assets/gifs/autocat.gif';
  static const String auzzie1 = 'assets/gifs/auzzie1.gif';
  static const String ava25 = 'assets/gifs/ava25.gif';
  static const String avanow1 = 'assets/gifs/avanow1.gif';
  static const String avanow28 = 'assets/gifs/avanow28.gif';
  static const String aviation1 = 'assets/gifs/aviation1.gif';
  static const String award = 'assets/gifs/award.gif';
  static const String awch88x31 = 'assets/gifs/awch_88x31.gif';
  static const String awebnow = 'assets/gifs/awebnow.gif';
  static const String aworldr = 'assets/gifs/aworldr.gif';
  static const String axcel = 'assets/gifs/axcel.gif';
  static const String aywren = 'assets/gifs/aywren.gif';
  static const String az01 = 'assets/gifs/az01.gif';
  static const String az02 = 'assets/gifs/az02.gif';
  static const String az03 = 'assets/gifs/az03.gif';
  static const String az1 = 'assets/gifs/az_1.gif';

  static final List<String> gifPaths = [
    SvgGifs.aaAni,
    SvgGifs.aaLogo,
    SvgGifs.aaaclipbut1,
    SvgGifs.aaextreme,
    SvgGifs.abWhite,
    SvgGifs.abYr,
    SvgGifs.ab,
    SvgGifs.ab03,
    SvgGifs.abcdirBanner6,
    SvgGifs.abcgiant,
    SvgGifs.aboutg,
    SvgGifs.abrbus,
    SvgGifs.abrowser,
    SvgGifs.absfree,
    SvgGifs.absoftLogo,
    SvgGifs.absoluteFtp,
    SvgGifs.absolutely,
    SvgGifs.acButtonFrobert,
    SvgGifs.acab,
    SvgGifs.acapickels,
    SvgGifs.acaza,
    SvgGifs.accelerating,
    SvgGifs.accursedFarmsAlienBlink,
    SvgGifs.acdsee,
    SvgGifs.aceftp,
    SvgGifs.aceplay,
    SvgGifs.achbus,
    SvgGifs.acid,
    SvgGifs.acidProd,
    SvgGifs.acidawards24,
    SvgGifs.acidfonts,
    SvgGifs.acidglossNet,
    SvgGifs.acidicdarkness,
    SvgGifs.acidlemon,
    SvgGifs.acmelogo,
    SvgGifs.activator,
    SvgGifs.activewin,
    SvgGifs.activeworlds,
    SvgGifs.addchannel,
    SvgGifs.addesigner,
    SvgGifs.addit1,
    SvgGifs.addme,
    SvgGifs.addmecom,
    SvgGifs.addpro,
    SvgGifs.adecline,
    SvgGifs.adlogo,
    SvgGifs.adobeAsanim1,
    SvgGifs.adobeAtmosphere,
    SvgGifs.adobeAuthorware,
    SvgGifs.adobeDreamweaver,
    SvgGifs.adobeFireworks,
    SvgGifs.adobeFlashGet,
    SvgGifs.adobeFpbutton,
    SvgGifs.adobeGetAuthorware,
    SvgGifs.adobeGetFlashPlayer,
    SvgGifs.adobeGetFlashplayer,
    SvgGifs.adobeGetFlashplayer2,
    SvgGifs.adobeGetShockPlayer,
    SvgGifs.adobeGetShockPlayer2,
    SvgGifs.adobeGetShockwave,
    SvgGifs.adobeGetShockwave2,
    SvgGifs.adobeGetShockwave20010813,
    SvgGifs.adobeGetShockwaveAuthorware,
    SvgGifs.adobeGetacro,
    SvgGifs.adobeGetacroread,
    SvgGifs.adobeGetareader,
    SvgGifs.adobeGetas2,
    SvgGifs.adobeGetauthorware,
    SvgGifs.adobeGetereader,
    SvgGifs.adobeGetflash,
    SvgGifs.adobeGetflash2,
    SvgGifs.adobeGetflash3,
    SvgGifs.adobeGetflash4,
    SvgGifs.adobeGetflashp,
    SvgGifs.adobeGolive,
    SvgGifs.adobeGolive2,
    SvgGifs.adobeMwmDir,
    SvgGifs.adobeMwmDirmw,
    SvgGifs.adobeMwmDw,
    SvgGifs.adobeMwmDwmx,
    SvgGifs.adobeMwmFla,
    SvgGifs.adobeMwmFlmx,
    SvgGifs.adobeMwmFw,
    SvgGifs.adobeMwmFwmx,
    SvgGifs.adobePhoto,
    SvgGifs.adobeSvg,
    SvgGifs.adobesvg,
    SvgGifs.adultchat,
    SvgGifs.aedit,
    SvgGifs.afBoton9,
    SvgGifs.afPixel,
    SvgGifs.afPsylab,
    SvgGifs.affcrack,
    SvgGifs.affection,
    SvgGifs.africapt,
    SvgGifs.afro,
    SvgGifs.afs,
    SvgGifs.afxbutton1,
    SvgGifs.agag,
    SvgGifs.agagamem,
    SvgGifs.agplv388x31,
    SvgGifs.ah,
    SvgGifs.aiboton,
    SvgGifs.aikiweb,
    SvgGifs.aim,
    SvgGifs.aimlink,
    SvgGifs.aimthings,
    SvgGifs.airmailnow,
    SvgGifs.akageobutton2,
    SvgGifs.akmmosBan,
    SvgGifs.aladdinnow,
    SvgGifs.aldema2,
    SvgGifs.aleash,
    SvgGifs.alertra,
    SvgGifs.alfart,
    SvgGifs.alienow,
    SvgGifs.alienwareButton,
    SvgGifs.alink02a,
    SvgGifs.allfree,
    SvgGifs.allfreethings,
    SvgGifs.alltits,
    SvgGifs.alohabook,
    SvgGifs.alphaIi,
    SvgGifs.alphaCentauri,
    SvgGifs.altavista,
    SvgGifs.altavista2,
    SvgGifs.amatsuki,
    SvgGifs.amazingFreeStuff,
    SvgGifs.amazon88x31,
    SvgGifs.amazon,
    SvgGifs.amazon2,
    SvgGifs.amazon3,
    SvgGifs.amazon4,
    SvgGifs.amazon5,
    SvgGifs.amdNow,
    SvgGifs.amdPowered,
    SvgGifs.americasdecline,
    SvgGifs.amftpnow,
    SvgGifs.amigaNews,
    SvgGifs.amigaNews2,
    SvgGifs.amiga,
    SvgGifs.amiga1200,
    SvgGifs.amigaAnim,
    SvgGifs.amigaFriendly,
    SvgGifs.amigaPower,
    SvgGifs.amigaRc5,
    SvgGifs.amigaamp,
    SvgGifs.amigademo,
    SvgGifs.amigaemu,
    SvgGifs.amigaos,
    SvgGifs.amigapow,
    SvgGifs.amigatm,
    SvgGifs.amircNow,
    SvgGifs.amiw2,
    SvgGifs.amyuoy1,
    SvgGifs.anClan88,
    SvgGifs.anarchyNow,
    SvgGifs.anarchy,
    SvgGifs.anarchy1,
    SvgGifs.anarchynow,
    SvgGifs.andysart,
    SvgGifs.angel99,
    SvgGifs.angelcat3,
    SvgGifs.angelfire,
    SvgGifs.angelkiss,
    SvgGifs.angellogo,
    SvgGifs.angellovebox,
    SvgGifs.angelzButton,
    SvgGifs.angyBan27,
    SvgGifs.aniFace,
    SvgGifs.aniPassale,
    SvgGifs.aniback1g,
    SvgGifs.anibanner,
    SvgGifs.anibutton,
    SvgGifs.anibuttonscifi,
    SvgGifs.anibuy3,
    SvgGifs.anigif,
    SvgGifs.anigifs,
    SvgGifs.anihome112g,
    SvgGifs.anilinkwired,
    SvgGifs.anilogo,
    SvgGifs.anima,
    SvgGifs.animagButton,
    SvgGifs.animatedbutton,
    SvgGifs.animation51,
    SvgGifs.animationsBackgroundsClipart,
    SvgGifs.animationshop,
    SvgGifs.animationstation,
    SvgGifs.animbat,
    SvgGifs.animbutton1,
    SvgGifs.anime100,
    SvgGifs.anime100games,
    SvgGifs.anime100green,
    SvgGifs.anime100red,
    SvgGifs.anime50,
    SvgGifs.animegay,
    SvgGifs.animeland,
    SvgGifs.animenation88x31,
    SvgGifs.animenation,
    SvgGifs.animexchange,
    SvgGifs.animicon,
    SvgGifs.aninext1g,
    SvgGifs.anipitstop,
    SvgGifs.annu,
    SvgGifs.anonymize,
    SvgGifs.another,
    SvgGifs.anreise,
    SvgGifs.anthrax,
    SvgGifs.antiButton,
    SvgGifs.antiaol,
    SvgGifs.anticodeandrun,
    SvgGifs.anticodeandrun2,
    SvgGifs.antifa,
    SvgGifs.antihentai,
    SvgGifs.antinazi,
    SvgGifs.antinft,
    SvgGifs.antisocialism,
    SvgGifs.antispicecool,
    SvgGifs.any,
    SvgGifs.any1,
    SvgGifs.any2,
    SvgGifs.any88x31,
    SvgGifs.anyBrowser,
    SvgGifs.anyBrowserAt,
    SvgGifs.anyBrowserEnhanced,
    SvgGifs.anyBrowserNow,
    SvgGifs.anybestviewed,
    SvgGifs.anybrow,
    SvgGifs.anybrowser,
    SvgGifs.anybrowser2,
    SvgGifs.anybrowser3,
    SvgGifs.anybrowser4,
    SvgGifs.anybrowser5,
    SvgGifs.anybrowser6,
    SvgGifs.anybrowser7,
    SvgGifs.anydamn,
    SvgGifs.anyieAnim,
    SvgGifs.anythingbut,
    SvgGifs.ao3gif,
    SvgGifs.aolSucks,
    SvgGifs.aolUser,
    SvgGifs.aol,
    SvgGifs.aolInstant3,
    SvgGifs.aolenterprise,
    SvgGifs.aolie,
    SvgGifs.aolim,
    SvgGifs.aolnetfind,
    SvgGifs.aolsux,
    SvgGifs.aoltosA,
    SvgGifs.apacheForrest,
    SvgGifs.apacheModPerl,
    SvgGifs.apachePowered,
    SvgGifs.apacheThanks,
    SvgGifs.apcProtect,
    SvgGifs.apc,
    SvgGifs.apcpagegr,
    SvgGifs.apngasm,
    SvgGifs.aponow,
    SvgGifs.appleCollect,
    SvgGifs.appleCollect2,
    SvgGifs.appleFatalError,
    SvgGifs.appleSpecial1,
    SvgGifs.appledust,
    SvgGifs.applelinks,
    SvgGifs.applelinks2,
    SvgGifs.applestore,
    SvgGifs.applyLogo,
    SvgGifs.applyLogo2,
    SvgGifs.approved,
    SvgGifs.approved508,
    SvgGifs.approvedasacpmember,
    SvgGifs.aqnow,
    SvgGifs.arachne,
    SvgGifs.arachne2,
    SvgGifs.arachno,
    SvgGifs.arcadevirusAv4,
    SvgGifs.archivers,
    SvgGifs.archivorock,
    SvgGifs.archlinux,
    SvgGifs.arcnet,
    SvgGifs.arena,
    SvgGifs.arizona,
    SvgGifs.armed,
    SvgGifs.armorgames,
    SvgGifs.artofdawn,
    SvgGifs.arttoday,
    SvgGifs.artwanted,
    SvgGifs.asacp,
    SvgGifs.asciicat,
    SvgGifs.asco88x313,
    SvgGifs.asexualsNow,
    SvgGifs.asswolfBanner,
    SvgGifs.asswolfTxt,
    SvgGifs.astaSmall,
    SvgGifs.asusClr19970504,
    SvgGifs.atariRead,
    SvgGifs.atari,
    SvgGifs.atariTimes,
    SvgGifs.atariWebring,
    SvgGifs.atarilogo,
    SvgGifs.atemplate8831,
    SvgGifs.ath2404,
    SvgGifs.atlas,
    SvgGifs.atmturbo,
    SvgGifs.atomic,
    SvgGifs.atomicansLink,
    SvgGifs.atomicdusticon,
    SvgGifs.atomicfireball,
    SvgGifs.atomicwarriors,
    SvgGifs.auction88x31,
    SvgGifs.auron,
    SvgGifs.auto,
    SvgGifs.autocat,
    SvgGifs.auzzie1,
    SvgGifs.ava25,
    SvgGifs.avanow1,
    SvgGifs.avanow28,
    SvgGifs.aviation1,
    SvgGifs.award,
    SvgGifs.awch88x31,
    SvgGifs.awebnow,
    SvgGifs.aworldr,
    SvgGifs.axcel,
    SvgGifs.aywren,
    SvgGifs.az01,
    SvgGifs.az02,
    SvgGifs.az03,
    SvgGifs.az1,
  ];
}
